### ISSUE TITLE
Define a Global Grid system - Mobile vs desktop breakpoints

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-web-platform#177]
## Definition of Done
Define a responsive grid for Web Platform, including max/min widths supported and mockups for the primary breakpoints (desktop/mobile)

## Tasks 
- [x] Decide on appropriate grid for our needs (columns, width, gutters, etc.)
- [x] Align future components to new grid
- [x] Decide on column/breakpoint scaling for components  between desktop and mobile 

- [x] Future: optimize components for responsive use as needed 

## References
- Protocol Containers: https://protocol.mozilla.org/patterns/templates/content-container.html 
- Protocol Breakpoints and Layouts (new): https://www.figma.com/file/JKjmrE0EjVqMmKHcyCaTYB/Protocol-%22Project-Poutine%22---Style-Guide?node-id=32%3A1815
- Desktop Grid Templates (marketing site): https://www.figma.com/file/L4z8XxuFrbGgN83oe3gjh5/Mozilla-Rally-%E2%80%93-Website-(rally.mozilla.org)?node-id=2297%3A2957 
- Mobile Grid Templates (marketing site): https://www.figma.com/file/L4z8XxuFrbGgN83oe3gjh5/Mozilla-Rally-%E2%80%93-Website-(rally.mozilla.org)?node-id=2297%3A2506
