### ISSUE TITLE
Global changes to settings

### ISSUE THREAD

**Issue by changecourse** [mozilla-rally/rally-web-platform#178]
## Definition of Done

Update the Settings subsections for consistency, clarity, and adherence to usability best practices.

## Tasks
- [ ] Align settings section to global grid (#177) 
- [x] Add Title and Summary section for each account subsection
- [x] Revise approach for labels (text above form field) vs. help text (below label and form field) vs. description text in form fields 
- [x] Improve error validation timing and approach
- [x] Toast notification approach for successful/failed changes based on action taken

**Comment by Carla-Moz** [comment]
"Revise approach for labels (text above form field) vs. help text (below label and form field) vs. description text in form fields"

@changecourse, which approach are we going for here for the labels and placeholder texts?

**Comment by Carla-Moz** [comment]
![Screen Shot 2021-12-16 at 3 59 48 PM](https://user-images.githubusercontent.com/88336547/146448209-b4109c77-2acc-40e1-9f60-b9789a6bfcbd.png)

Does the above capture what you've suggested, @changecourse ?
