### ISSUE TITLE
Account Settings (New)

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla-rally/rally-web-platform#184]
## Story

As a User, I want to be able to access my account so that I can update my settings. 

## Definition of Done

When the user can update their email, password, enable 2FA, and leave Rally

## Tasks 
- [x] Create the components for the default page
- [x] Create update email page
- [x] Update password page
- [x] Enable 2FA page
- [x] Leave Rally button and modal 
- [x] Navbar with user icon 
- [x] Log out functionality
