### ISSUE TITLE
Refine create account & sign in flows

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#207]
## Story

Design create account & sign in flows using the new design system & grids.

## Definition of Done 

- The end to end flow of creating an account and subsequently signing in is designed and ready to be implemented in code.
- The behaviors (if any unusual ones) are documented within Figma.
- The flow is ready to implement and shared with Engineering.

## Tasks 

- [x] Put together phases & tasks for...
  - [x] Create Account
  - [x] Sign in

- [x] Design end to end flow using new design system & grid...
  - [x] Create Account
  - [ ] Sign in

- [ ] Review it with the team on Monday during cross functional 3/14
