### ISSUE TITLE
Review user flow for accessibility issues & identify resolutions

### ISSUE THREAD

**Issue by mkhandekar** [mozilla-rally/rally-web-platform#264]
## Goal

Review user flow for accessibility issues & identify resolutions (for create account, sign in, account settings)

## Definition of Done

Accessibility review of user flow is complete for accessibility issues & identify resolutions

## Tasks

- [x] Check all elements in Stark [(figma plugin)](https://www.figma.com/community/plugin/732603254453395948/Stark)
  - [x] Meghana did the Create Account / Sign in
  - [x] Casey to do the Manage Account section
- [x] Document what fails using screenshots 
- [x] Identify local resolution (if the element doesn't repeat elsewhere) 
- [x] Identify global resolution (if the component repeats elsewhere) 
- [x] @tangcasey to implement all iterations
