### ISSUE TITLE
Epic: Create Account Flow

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#268]
Stories under this Epic:

- [ ] Align to grid 
- [ ] New create account styles [(Account Creation Flow)](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/?node-id=3%3A107)
- [ ] Fix google sign-in bug
- [ ] Remove google pop-up flow and place within card container 
- [ ] Redirect users to the app after confirming email
