### ISSUE TITLE
[Epic 2]: Privacy Policy page

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#269]
Stories under this Epic:
- [ ] Align to grid
- [ ] Remove fade 
- [ ] Iterate on [content](https://docs.google.com/document/d/1ndysAp0gtMoQRZ82-fuhhjGKzWIv5r-05aMSr-amtg8/edit#heading=h.9o9aqo21vh4b) to integrate the fact that the experience includes email/pass/accounts. Leave all else the same.
- [ ] Legal approval: Al has given a first-pass approval
