### ISSUE TITLE
[Epic 3]: Demographic Survey Updates

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#270]
Stories under this Epic:

### **Content** @mkhandekar 
[DRAFT: Rally Copy / Legal Review](https://docs.google.com/document/d/1v91NCZHkAqj_qUf44Q-bN2LC3VMngdo2SNagZeet7S8/edit#)
- [x] Bruce & Meghana meet to discuss changes
- [x] Update intro & fix typos
- [x] Convert zip code to look-up drop-down
- [x] Change income to narrower ranges
- [x] Make questions as inclusive as possible (questions, options, open text fields, etc)
- [x] Add a new question: How did you hear about us?
- [x] Refine question order to encourage completion of key questions
- [x] @betling @javaun to review and help finalize changes week of April 18, 2022
- [x] Get legal (if needed) and partner (if needed) 👍

### **Design** @tangcasey 
- [ ] Create page in Figma with new typographic styles

### **Front end** @Carla-Moz 
- [x] Align to updated grid
- [x] Remove fade and make it a fully viewable and scroll-able page 
- [x] Implement updated content & design
