### ISSUE TITLE
[Epic 5]: Delete your Rally account

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#271]
Stories under this Epic:

### Content @mkhandekar 
- [x] Wait for legal to take a pass https://github.com/mozilla-rally/internal/issues/491
- [x] Iterate on language: passive to active language, simplify sentence structure, more conversational
- [x] review with legal team 

### Design @tangcasey 
- [x] Make these two pages (modal & subsequent page) look as similar as possible 
- [x] Add friction to deleting an account

### Front end @aaga  
- [x] Implement updated content & design (see Meghana's comment below)
- [x] Collaborate with @tangcasey to implement any tricky behavior or open questions

### Engineering 
- [x] #286 
- [x] #291

**Comment by mkhandekar** [comment]
# Modals content

**Note for @thomik-corp: Please check the Figma link for each modal to check typography styles & sizes, overall modal size and spacing between components, button styles, images, etc**

**Note: @tangcasey might need to export some pngs if needed (there are a couple of illustrations in these screens)**

---

## When you click Delete Account in account settings — [See in Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2547%3A62298)

_Modal content_ 

Title: Delete your Rally account
Subtitle: Thank you for helping make the Internet a little better
**Deleting your Rally account means:**
- **Rally will stop collecting all data.**
- **You will stop contributing browsing data** to studies you may have joined. 
- **Rally will delete all your profile information.**
- **Rally will delete all your data from open studies you had joined.** Researchers may still have access to browsing data you contributed to **completed studies**.

_Call to action buttons:_
[Cancel] [Delete your Rally account]
Cancel takes you back to account setting's landing page. Delete your Rally account opens subsequent modal.

![Delete your Rally account](https://user-images.githubusercontent.com/1598889/167741144-f9c43fdf-ae56-4612-b29b-7fa5569f4353.png)

---

## When you click Delete your Rally account from the previous page — [See in Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2547%3A62298)

_Modal content_ 

Title: Are you sure?
Body: This will permanently delete your Rally account. 

[Cancel] [Delete your Rally account]
Cancel closes this modal. Delete your Rally account deletes user account!, then takes you to the subsequent logged-out screen on the Rally website (which re-iterates the same content). 

![Confirmation](https://user-images.githubusercontent.com/1598889/167741252-05f60b3b-dbf4-4bfc-9351-b78029e2e7e5.png)

---

## When you click Delete your Rally account from the previous modal — [See in Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2547%3A62298)

_Modal content_ 

Title: Thank you for being part of Rally!
Subtitle: We appreciate your help in making the Internet a little better. 
**You have deleted your Rally account.** This means:

- Rally will stop collecting all data.
- You will stop contributing browsing data to studies you may have joined. 
- Rally will delete all your profile information.
- Rally will delete all your data from the open studies you joined. Researchers may still have access to browsing data you contributed to completed studies.

We hope you come back anytime. Feel free to stay in touch with us by [signing up for our newsletter](https://rally.mozilla.org/newsletter/index.html) or [add us on Twitter](https://twitter.com/MozillaRally).

![Mozilla Rally – Account Settings, Thank you for being part of Rally (default)](https://user-images.githubusercontent.com/1598889/167742070-c4a3cf15-b08e-4346-aa50-5a43ece42c8e.png)

**Comment by aaga** [comment]
@mkhandekar Thank you so much for this well-documented ticket!

I have a question about the last screen: the screenshot (given the nav bar) makes it look like this should live on the main Rally website as an offboard URL (i.e. separate from the RWP). However the URL suggests that it is part of the RWP. Which do we want?

For reference, we currently do the former with the Core Add-on. We direct users here: https://rally.mozilla.org/leaving-rally/index.html
