### ISSUE TITLE
[Epic 4]: Studies Page

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/rally-web-platform#273]
MVP - only the Facebook Pixel Hunt study will be displayed and available.

Stories under this epic:

### UX @tangcasey 
Supporting: @mkhandekar. [See FigJam for other notes we took together](https://www.figma.com/file/6CaVFu8Jxs8p1NccbdzYdB/Planning-%26-user-flows---Q1-2022?node-id=0%3A1).

- [x] **Improve Introductory content** (or onboarding-style content) on Current Studies. It should let users know if and when they are done or need to resolve an issue.
- [x] **Users have the ability to join a study,** which enables these options / functionality
  - [x] Join Study button opens up a modal
  - [x] Install Chrome extension 
  - Notes
    - Casey, [see **draft** of the new modal content](https://docs.google.com/document/d/1v91NCZHkAqj_qUf44Q-bN2LC3VMngdo2SNagZeet7S8/edit?disco=AAAAXmIDS98) (this is to be reviewed by Javaun, legal, etc) that tells a user within the modal what steps are next — sharing in case if helps you — we can keep iterating. Related ticket: https://github.com/mozilla-rally/internal/issues/491. 
    - Casey, in the same doc ^ that my recommendation for changing the "Accept & Enroll" language to "[Cancel] [Join study on the Chrome store]" — again, we can keep iterating. 
- [x] **Users have the ability to see that they have joined a study**, which enables these options / functionality 
  - [x] If a user has properly joined a study, available functionality is Leave study (add friction)
  - [x] if a user has not properly joined a study via Chrome store, available functionality is to resolve issues with studies (finish joining study by going to the Chrome store to add the study extension)
  - Notes
    - Carla said it's possible to add a date stamp for when the user joined the study

### Front end @thomik-corp 
- [x] #403
- [x] Collaborate with @tangcasey to implement any tricky behavior or open questions
- [x] Make Join Study and Leave Study modals a fixed height (or max vertical percentage, or something, so that it doesn't take over the entire page on larger screens) - consult with @tangcasey for details

## Chrome store 
Original Chrome store [planning documentation](https://docs.google.com/document/d/1otD_z8K0dYR3JPZDU0XkScLVQ28RA8MYmx2U-B627cU/edit#heading=h.ulh8fhx1pisj)

### UX @tangcasey 
**_Some possibilities_** for branding / design work on the Chrome store to introduce Rally and the study a little more... 
   - [ ] create new image that tells a story about particular study and research possibilities
   - [ ] update Privacy practices, etc (secondary nav in store)
   - [ ]  1,2,3 steps of how rally works
   - [ ] image showing the name of the extension you're installing and research possibilities
   - [ ] Decide brand architecture: partner logo, naming could include partner and Rally's name
   - [ ] If existing Rally website is open, jump to the tab showing Current Studies
   - [ ] If no rally website is open, replace the Chrome store tab showing current studies OR open and jump to new tab showing Current Studies

### Eng
   - [x] #284

**Comment by mkhandekar** [comment]
# Modals content

**Note for Ashish: Please check the Figma link for each modal to check typography styles & sizes, overall modal size and spacing between components, button styles, images, etc**

**Note: @tangcasey might need to export some pngs if needed (there are a couple of illustrations in these modals)**

---

## When you click Join Study from a card — [See in Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2547%3A62248)

_Top area:_ 
[Logo] [Study name]
by [Researcher name] | Ends: [End date]

_Top area specifically for the Markup:_
[Markup logo] Facebook Pixel Hunt
by Mozilla Rally and the Markup | Ends: Jul 13, 2022

_Content within the modal in a scrollable box:_
You are joining the Facebook Pixel Hunt, a study by Mozilla Rally and The Markup.

**How to join this study**

1. Click on "Add study extension” below. This will open the Chrome Web Store.
2. There, click on "Add to Chrome.” This will add this study's extension to your browser.
3. You will be brought back to the Rally website. Here you will see that you have joined the study and are contributing your browsing data. 

**About the study**
The Markup will use the browsing data collected in this study to map Facebook's tracking pixel network across the web. Read more about this study on the Rally website. The Markup will publish its findings as news stories at themarkup.org.

**Leaving the study**
You can leave the study anytime from the Rally Studies page, found by clicking on the Rally icon [flag-icon] in your browser toolbar.

_Call to action buttons:_
[Cancel] [Add study extension]
Cancel closes this modal. Add study extension takes you to this study's web store URL.

![image](https://user-images.githubusercontent.com/1598889/167732439-eaff94aa-0b61-4d0b-bf2b-88a9e8513611.png)

---

## When you click Leave this study from a card's dropdown — [See in Figma](https://www.figma.com/file/zwCNcZbWKB6uOBRTNXomYo/Mozilla-Rally-%E2%80%93-Web-Platform?node-id=2547%3A62235)

_Modal content_

Title: Leave this study
Subtitle: You're free to come and go as you please!

**Leaving a study means:**

- You will only be leaving this study. You will continue contributing your browsing data to any other studies you've joined.
- You will stop contributing browsing data to this study and the researchers leading this study.
- Rally will delete all your data from this study.

[Cancel] [Leave study]
Cancel closes this modal. Leave study removes the user from the study, and when the modal closes, user sees a notification/toast that let's them know they have successfully left the study.

![image](https://user-images.githubusercontent.com/1598889/167733181-f8682cf6-ab20-48ff-97a8-e0f82c0c4872.png)

**Comment by thomik-corp** [comment]
Actually most of these changes were committed in my previous pull requests:
- https://github.com/mozilla-rally/rally-web-platform/pull/337
- https://github.com/mozilla-rally/rally-web-platform/pull/395

There is a followup pull request that is fixing the delta:
- https://github.com/mozilla-rally/rally-web-platform/pull/404
