### ISSUE TITLE
Rally homepage /  How it works section - content and/or design

### ISSUE THREAD

**Issue by tangcasey** [mozilla-rally/rally-web-platform#701]

**Comment by compzilla** [comment]
Either @rhelmer or @jepstein are putting together a mock-up. @knowtheory has seen the copy, and I've passed it on to Rob and Jonathan. I'm using the term "mock-up" to mean that I've asked them to make a test site that is not live, with small copy changes to the top of the fold and then some more substantial changes to the bottom "How it Works" from a template that Threespot had already made and is being used for the two landing pages for Compensation vs. Donation Model.

**Comment by compzilla** [comment]
**Above the fold:**
**Header:** 
**Button CTA:** Join Rally / Add Extension (A/B test)
Change CTA button color to green #54FFBD

Should have five states: 
1. Normal
2. Hover (darker)
3. Pressed (even darker)
4. Focus [[[[Is there an ADA recommendation - or do we decide? How is this activated by user? @tangcasey ]]]]]
5. Disabled (super faded)

**Headline:**
    It’s your data. Use it for change. [[[Decision was made w input from Casey, Sydette, Ted, Kennedy, and Amy]]]

—> Change color of green highlight to YELLOW (to match onboarding windows)        

**Text:**
Big Tech has built its success by exploiting your personal information (aka data). Mozilla Rally is a simple extension that puts your data to work exposing this issue. Data from people like you has already uncovered:
FAFSA sending personal data about applicants (students? @knowtheory - which?) to Facebook
Hospitals sending sensitive patient information to Facebook

**Button CTA:** Join Rally/Add Extension  [[[for A/B testing]]]

**Comment by compzilla** [comment]
**Below the fold:**
How it Works

[This is a screenshot from the landing pages that Rob and I mocked up. Please delete the CTA Button under step 1. Let’s just have 3 simple steps. (And then one more CTA down below.) ]

**Comment by compzilla** [comment]
(Can you add screenshots in Github? I'm trying to figure it out...)

**Comment by compzilla** [comment]
I can't figure out how to add screenshots, so I'm adding this document which has the screenshot. https://docs.google.com/document/d/19cG_jfe-zxBLhW4AVLZno_3HkqPXIl363wL__FSeGtk/edit#

**Comment by compzilla** [comment]
From @rhelmer -  It looks like focus for these elements has been purposely disabled using [https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex](https://www.google.com/url?q=https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex&sa=D&source=docs&ust=1664858599253322&usg=AOvVaw0WxhDOpwxLBUisuht8Z_hU) - you can see examples on the page at that link, but generally focus for HTML buttons is signified by a border (and yeah it is one way to be accessible to assistive devices like screen readers!)

**Comment by compzilla** [comment]
I asked @rhelmer if we could re-instate FOCUS state on buttons for ADA, usability, and inclusivity reasons.

**Comment by compzilla** [comment]
At the bottom of the How it Works section will be: 
When we RALLY together, we can make BIG changes.

**Comment by compzilla** [comment]
@compzilla WIll work on new subtitle for How it Works (b/c what is listed is HOW YOU WORK TO SIGN UP TO GIVE YOUR DATA), but that doesn't really roll off the tongue.

**Comment by jepstein** [comment]
@compzilla you can see a version at https://elegant-griffin-14cb7c.netlify.app/.
This is just the text updates. I did not do the style or text changes for the buttons.

**Comment by compzilla** [comment]
Happy to keep track of change requests here @jepstein. Thanks for your work doing this. From a user acquisition perspective, I'll make some design requests, then will leave it up to @tangcasey to make design decisions: 

**ABOVE THE FOLD**

**Need to have:**
- [ ] Change green highlight to any color but green (yellow?) b/c of the next step.
- [ ] Change CTA buttons on this page to green (We will A/B test colors and text of the CTA's in the future - decision was made for green on 9/15 taking into consideration user acquisition best practice, brand, harmony, and contrast w surrounding colors) - Threespot has made recommendations for the color)
- [ ] Reduce the padding between the header and the "It's your data. Use it for change" so that a bit more of a peek of the yellow quote box towards the bottom of this window shows, indicating to users they can scroll down.
- [ ] The bullets in top section seem to live outside the left margin - design call. 

**Nice to have: (not MVP - so maybe for next iteration)**
- [ ] A third bullet for value prop - only two bullets does not look good. Looking for ANYBODY's input here. (I'm only familiar w results of Pixel Hunt study.) I wrote three bullets for the Value Prop in the Onboarding Flow - can these be the same ones?
- [ ] Each line of the bullet should not take up two lines - so if the size of the right graphic were reduced, they would each fit on one line - but that might be really complicated to make the whole graphic smaller b/c it is a composite of many images - seems like this would be a heavy lift for MVP.
- [ ] Decrease padding above the header if we need more room for a third bullet. 
- [ ] Best practice dictates that text in CTA should be larger than the surrounding body text - resulting in larger CTA buttons - this might be too much for MVP


**BELOW THE FOLD:**

**Need to have:**
- [ ] Decrease spacing between "You can help..." and the numbered lines - and between the numbered lines
- [ ] In No. 1 - take out "to" and add a period to the end.
- [ ] Add a CENTERED green CTA button between #1 and #2. 
- [ ] Decrease spacing between #3 and the "When we RALLY together..."
- [ ] The screenshot on the right in #3 is of a BLACK flag, and the new Mozilla Rally extension is a GREEN flag. This may cause confusion. @tangcasey, can you photoshop that to a green flag? (I have too many bookmarks/shortcuts to take a new screenshot - sorry.) If this is a big lift, move to "Nice to have."
- [ ] Remove CTA from under "When we RALLY together..."

**Nice to have:**
- [ ] Text size hierarchy is all over the place here, but will let @tangcasey make the call - it's like this in the Threespot template, and therefore shows up here and on landing pages.
- [ ] Swap out the BLACK flag logo in #3 for a GREEN one. (Let me know if this is a big lift.)
- [ ] Changing the CTA button to green plus the non-brand-color red circles around the numbers (Threespot template) make this section a bit too "merry" for me personally - @tangcasey up to you to make the call - this has nothing to do w user acquisition - just personal taste :) Is it a big lift to change the color of the red circles? If so, to what color @tangcasey?
